### ISSUE TITLE
"python-keyring" level in pass not wanted

### ISSUE THREAD

**Issue by huntermatthews** [nazarewk/keyring_pass#1]
First, I started playing with this and it seems to be _exactly_ what I want. The only niggle of an issue I had was that keyring_pass introduces a top level directory in pass called "python-keyring"
(in the get_key() function).

I tested just having this directory be a symlink to our "api" subsection and that worked perfectly. I also tried it as a symlink to "." (to basically null it out) and that also worked perfectly.

My core issue is that with that addition, I can't use keyring_pass to get all of our creds - I could only use it to get the ones _created_ by keyring_pass. We definitely want to be able to share/reuse credentials between python scripts and other systems (bash, ruby, maybe perl). 

Is there a technical reason or security reason for this extra level that I've missed?

**Comment by nazarewk** [comment]
Added `v0.7.0` making it possible to configure that prefix

**Comment by matthewsht** [comment]
I forgot to say "Thank You" at the time - Thank you.
