### ISSUE TITLE
Compatibility with poetry 1.71

### ISSUE THREAD

**Issue by qckpckt** [nazarewk/keyring_pass#19]
Hi,

I'd like to use `keyring_pass` as a backend for storing access tokens for a private gitlab pypi registry in poetry. Unfortunately, the current dependency on keyring (`^23.9.3`) precludes this:

```>>> poetry self add keyring-pass               
Using version ^0.8.1 for keyring-pass

Updating dependencies
Resolving dependencies... (0.0s)

Because no versions of keyring-pass match >0.8.1,<0.9.0
 and keyring-pass (0.8.1) depends on keyring (>=23.9.3,<24.0.0), keyring-pass (>=0.8.1,<0.9.0) requires keyring (>=23.9.3,<24.0.0).
And because poetry (1.7.1) depends on keyring (>=24.0.0,<25.0.0), keyring-pass (>=0.8.1,<0.9.0) is incompatible with poetry (1.7.1).
So, because poetry-instance depends on both poetry (1.7.1) and keyring-pass (^0.8.1), version solving failed.
```
Is there actually a breaking change in keyring 24.*, or could this be addressed with a dependency bump? If this is an unknown i'd be happy to have a go at investigating. :)

**Comment by nazarewk** [comment]
It is unknown, but I think having it as `> 23.9.3` would be ok. I can fix it and release on Monday.

**Comment by nazarewk** [comment]
fixed in https://github.com/nazarewk/keyring_pass/releases/tag/v0.9.0

**Comment by qckpckt** [comment]
Amazing ❤️
