### ISSUE TITLE
/usr/lib/python-exec/python3.11/python: No module named keyring_pass.__main__; 'keyring_pass' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by formula-spectre** [nazarewk/keyring_pass#23]
I installed keyring_pass via `pip install --break-system-packages keyring-pass` as a quick and dirty solution before I modify the ebuild and install it system wide (I know it's dangerous, it was just for testing);  
but `python -m keyring_pass` gives this error:  
`/usr/lib/python-exec/python3.11/python: No module named keyring_pass.__main__; 'keyring_pass' is a package and cannot be directly executed`  
am I doing something wrong? I'm following the readme to verify that it's working; my `~/.config/python_keyring/keyringrc.cfg` has only the following:
```
[backend]
default-keyring = keyring_pass.PasswordStoreBackend
```
do I need to put in there something else? I use vanilla pass, not gopass (tho I might migrate to it)

**Comment by nazarewk** [comment]
Yeah, it has something to do with new Python being more restrictive. I'll move the test to `__main__.py` when I find some free time.

Otherwise you should be able to use it just fine through `keyring`.

**Comment by formula-spectre** [comment]
is there any way I can help? I know python but I never packaged anything seriously with it, just glue code or toys. PEP standards changes very often, so I'm kinda clueless there. but nontheless, if I can help I will gladly do so!

**Comment by nazarewk** [comment]
I think it's just about moving `if __name__ == '__main__':` block content to a separate `__main__.py` file

**Comment by formula-spectre** [comment]
forgot to close this lol
