### ISSUE TITLE
ImportError with the latest python-keyring

### ISSUE THREAD

**Issue by azmeuk** [nazarewk/keyring_pass#6]
With python-keyring 23.9.0, using keyring_pass raises an `ImportError`

```python
>>> import keyring_pass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/keyring_pass/__init__.py", line 10, in <module>
    from keyring.util import properties, platform_ as platform
ImportError: cannot import name 'properties' from 'keyring.util' (/usr/lib/python3.10/site-packages/keyring/util/__init__.py)
```

According to [this issue](https://github.com/jaraco/keyring/issues/593), the missing property is [reintroduced with 23.9.1](https://github.com/jaraco/keyring/blob/main/CHANGES.rst#v2391), but with a deprecation warning, so this exception will come back in the future.

**Comment by formula-spectre** [comment]
~~I would like to point out that this problem presents itself as of today (04/03/24), so maybe a dep bump is needed?~~  
my bad, the one I was installing was still @ 0.77, so don't pay attention to this comment
